version: '3.8'

services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    image: 'server_image'
    env_file:
      - .env.development
    ports:
      - '3333:3333'

  testDb:
    image: mysql:latest
    restart: always
    ports:
      - '3310:3306'
    environment:
      MYSQL_USER: 'prisma'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'test'

  next:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/client/Dockerfile
    image: 'client_image'
    env_file:
      - .env.development
    ports:
      - '4200:4200'
