name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - frontend/sprint8/chore/vercel-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build and Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t docker.io/baginskijakub/client_image:${{ github.sha }} -f ./apps/client/Dockerfile .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push docker.io/baginskijakub/client_image:${{ github.sha }}

      - name: Deploy to Vercel
        uses: vercel/actions@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: prj_dEkbC0GpW8L1yv337bwzO2uoDAiJ
          vercel-args: '--prod'
