name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
      - frontend/sprint7/chore/cd-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12

      - name: Clear cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm i

      - name: Build Next.js app
        run: npm run client:build

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::052774457512:role/DeployRole
          role-session-name: GitHub-Action-Role
          aws-region: eu-north-1
