name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
      - frontend/sprint7/chore/cd-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12

      - name: Clear cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm i

      - name: Build Next.js app
        run: npm run client:build

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=eu-north-1" >> ~/.aws/config

      - name: Deploy to Amplify
        run: |
          npm install -g @aws-amplify/cli
          npx amplify configure --usage-data-off
          cd apps/client
          npx amplify pull --appId d1zfh8hd97i0di --accessKeyId ${{ secrets.AWS_ACCESS_KEY_ID }} --secretAccessKey ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          npx amplify push --yes
