name: CI Pipeline (SEP4YG2)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "apps/server**"
jobs:
  tests:
    name: Run tests on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout brach
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12
      - name: Install dependencies
        run: npm install
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_TEST }}" > .env
      - name: Push schema to test database
        run: npm run server:test:db:push
      - name: Run Tests
        run: npm run server:test
