name: CI Pipeline (SEP4YG2)

on:
  workflow_dispatch:
  push:
    branches: [ backend/proof-of-concept]
    paths:
      - 'backend/apps/server**'
  pull_request:
    branches: [ dev]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: npm install
      - name: Run Tests
        run: npx nx test server